### ISSUE TITLE
Error: Invariant failed: You should not use <withRouter(App) /> outside a <Router>

### ISSUE THREAD

**Issue by neilbmclaughlin** [pact-foundation/pact-workshop-js#3] opened 2020-05-18 09:47 UTC
Node: v10.19.0
MacOS: 10.15.4 

I get this error then running `npm start --prefix consumer` from step1 on a clean install of the workshop.

![Screenshot 2020-05-18 at 10 41 21](https://user-images.githubusercontent.com/212582/82198403-2b0dfa80-98f4-11ea-9fb2-d2fc27e8d645.png)

**Comment by jaucourt** [comment] 2020-05-18 10:03
This can be resolved by fixing the version of react-router to 3.2.6, rather than latest as it is in the package.json for the consumer

**Comment by neilbmclaughlin** [comment] 2020-05-18 13:24
Thanks. Switching the version for react-router to 3.2.6 fixes the above problem but reveals another.

![Screenshot 2020-05-18 at 14 23 49](https://user-images.githubusercontent.com/212582/82218062-37558000-9913-11ea-8790-db66a390a13d.png)

**Comment by neilbmclaughlin** [comment] 2020-05-19 09:07
The original problem (Error: Invariant failed) is fixed by #4

**Comment by shilgam** [comment] 2020-05-24 21:20
I was able to successfully get intended behaviour (got an exception `Error: Network Error`) by installing dependencies without modifying `package-lock.json` file. I.e.:

```
npm ci
npm start
```

**Comment by ShivamLatawa** [comment] 2021-01-05 06:30
This happens because the latest version of react-router doesn't allow to wrap component in withRouter as the api has changed. I fixed it by removing the withRouter from App and using the useHistory() hook from react-router-dom. Like this:

`
import React, { useCallback, useEffect, useReducer } from "react";
import { Link } from "react-router-dom";
import "spectre.css/dist/spectre.min.css";
import "spectre.css/dist/spectre-icons.min.css";
import "spectre.css/dist/spectre-exp.min.css";
import Heading from "./Heading";
import Layout from "./Layout";
import API from "./api";
import PropTypes from "prop-types";
import { useHistory } from "react-router-dom";

const productPropTypes = {
  product: PropTypes.shape({
    id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
  }).isRequired,
};

function ProductTableRow(props) {
  return (
    <tr>
      <td>{props.product.name}</td>
      <td>{props.product.type}</td>
      <td>
        <Link
          className="btn btn-link"
          to={{
            pathname: "/products/" + props.product.id,
            state: {
              product: props.product,
            },
          }}
        >
          See more!
        </Link>
      </td>
    </tr>
  );
}
ProductTableRow.propTypes = productPropTypes;

function ProductTable(props) {
  let products = props.products.map((p) => (
    <ProductTableRow key={p.id} product={p} />
  ));
  return (
    <table className="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Type</th>
          <th />
        </tr>
      </thead>
      <tbody>{products}</tbody>
    </table>
  );
}

ProductTable.propTypes = {
  products: PropTypes.arrayOf(productPropTypes.product),
};

function App() {
  const [state, setState] = useReducer(
    (state, newState) => ({ ...state, ...newState }),
    { loading: true, searchText: "", products: [], visibleProducts: [] }
  );
  const history = useHistory();

  const determineVisibleProducts = () => {
    const findProducts = (search) => {
      search = search.toLowerCase();
      return state.products.filter(
        (p) =>
          p.id.toLowerCase().includes(search) ||
          p.name.toLowerCase().includes(search) ||
          p.type.toLowerCase().includes(search)
      );
    };
    setState((s) => {
      return {
        visibleProducts: s.searchText ? findProducts(s.searchText) : s.products,
      };
    });
  };
  const memoizedDetermineVisibleProducts = useCallback(
    determineVisibleProducts,
    state.visibleProducts
  );

  useEffect(() => {
    API.getAllProducts()
      .then((r) => {
        setState({
          loading: false,
          products: r,
        });
        memoizedDetermineVisibleProducts();
      })
      .catch((e) => {
        history.push({
          pathname: "/error",
          state: {
            error: e.toString(),
          },
        });
      });
  }, [history, memoizedDetermineVisibleProducts]);

  const onSearchTextChange = (e) => {
    setState({
      searchText: e.target.value,
    });
    memoizedDetermineVisibleProducts();
  };

  return (
    <Layout>
      <Heading text="Products" href="/" />
      <div className="form-group col-2">
        <label className="form-label" htmlFor="input-product-search">
          Search
        </label>
        <input
          id="input-product-search"
          className="form-input"
          type="text"
          value={state.searchText}
          onChange={onSearchTextChange}
        />
      </div>
      {state.loading ? (
        <div className="loading loading-lg centered" />
      ) : (
        <ProductTable products={state.visibleProducts} />
      )}
    </Layout>
  );
}

export default App;

`

**Comment by mefellows** [comment] 2021-05-12 02:35
Yeah, it looks like an upgrade needs to happen.

For now `npm ci` should ensure the correct version from package lock is used. It's probably not a big change to the react app, a PR would be welcome!

**Closed** 2021-05-12 02:57 UTC
